version: '3'

services:
  database:
    image: postgres:10
    container_name: database
    hostname: database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nomenclator
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:5432:5432"
    networks:
      - localnet


  redis-master:
    image: bitnami/redis:latest
    container_name: redis-master
    hostname: redis-master
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=password123
    ports:
      - "6379:6379"
    volumes:
      - redis_master_data:/bitnami/redis-master/data
    restart: always
    networks:
      - localnet


  redis-slave:
    image: bitnami/redis:latest
    container_name: redis-slave
    hostname: redis-slave
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=password123
      - REDIS_PASSWORD=password123
    ports:
      - "63791:6379"
    volumes:
      - redis_slave_data:/bitnami/redis-slave/data
    restart: always
    networks:
      - localnet

networks:
  localnet:
    driver: bridge

volumes:
  pgdata:
  redis_master_data:
    driver: local
  redis_slave_data:
    driver: local

